[build]
builder = "nixpacks"
buildCommand = "npm run railway-deploy"

[deploy]
startCommand = "cd .next/standalone && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 3
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[nixpacks]
nodejs-version = "20"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
CSRF_SECRET = "your-csrf-secret-change-in-production"
MONGODB_URI = "mongodb+srv://Avestami:xKuiw9ie7AacuMrI@blackbird.3qpqiyp.mongodb.net/blackbird?retryWrites=true&w=majority"
DATABASE_URL = "mongodb+srv://Avestami:xKuiw9ie7AacuMrI@blackbird.3qpqiyp.mongodb.net/blackbird?retryWrites=true&w=majority"
GEMINI_API_KEY = "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"
NEXTAUTH_SECRET = "your-nextauth-secret-change-in-production"
NEXTAUTH_URL = "https://blackbird-production.up.railway.app/"
