[build]
builder = "nixpacks"
buildCommand = "node scripts/custom-build.js"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
nixpkgs = ["nodejs_20"]