[build]
builder = "nixpacks"
buildCommand = "npm run railway-deploy"

[deploy]
startCommand = "cd .next/standalone && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "always"
restartPolicyMaxRetries = 5

[nixpacks]
nodejs-version = "20"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_RUNTIME = "nodejs" 