[build]
builder = "nixpacks"
buildCommand = "node scripts/custom-build.js"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[nixpacks]
nodejs-version = "20" 