[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[nixpacks]
nodejs-version = "20" 